### ISSUE TITLE
Reduce slope measurement update frequency

### ISSUE THREAD

**Issue by grst** [SponringDominik/Slope-Sensor#3]
I suggest to reduce the update frequency of the display to maybe 200-300ms when in slope measuring mode. I believe this would enhance readability in cold conditions.

**Comment by SponringDominik** [comment]
Tests have shown that a update frequency of 200ms works well. At slower update frequencies, it becomes more difficult to detect a difference between tilt and temperature measurement, as there is no indicator for the actual measurement mode.
-> Update frequency set to 200ms
